<?

$ilng = array (
	"title" => "Vložení obrázku",
	"undertitle" => "Možnost vložení obrázkù do textu.",
	"imgpath" => "Cesta k obrázku:",
	"explore" => "Procházet...",
	"alternativtext" => "Alternativní text:",
	"imgtitle" => "Popis obrázku:",
	"imgsize" => "Rozmìry:",
	"imgalign" => "Zarovnání:",
	"notset" => "nenastaveno",
	"left" => "vlevo",
	"right" => "vpravo",
	"top" => "k vrcholu",
	"bottom" => "ke spodku",
	"middle" => "na støed",
	"absmiddle" => "absolutnì na støed",
	"absbottom" => "absolutnì ke spodku",
	"baseline" => "na základnu",
	"marginleft" => "Odsazení z leva:",
	"margintop" => "Odsazení od vrchu:",
	"marginbottom" => "Odsazení ze spod:",
	"marginright" => "Odsazení z prava:",
	"border" => "Ohranièení:",
	"uploadnewimg" => "Nahrát na server nové obrázky",
	"insert" => "Vložit",
	"cancel" => "Zrušit",
	"testtext" => "Zde je testovací text. Mùžete mìnit vlastnosti obrázku pomocí nástrojù nalevo a zde uvidíte výsledný efekt.",
	"explorer" => "Prohlížeè obrázkù na serveru",
	"explorerdescription" => "Pomocí tohoto nástroje mùžete jednoduše prohlížet obrázky dostupné na serveru.",
	"selectdir" => "Zvolit adresáø:",
	"backtoexplore" => "Zpìt na prohlížení",
	"uploadertoserver" => "Uploader obrázkù na server",
	"uploadertoserverdesc" => "Zde mùžete pøidat nové obrázky na server.",
	"loadingimginfo" => "Naèítám informace o obrázku...",
	"proportions" => "Zachovávát pomìr stran",
	"doaslink" => "Vložit jako náhled s možností zvìtšení",
	"picture" => "Obrázek",
	"uploadtodir" => "Nahrát do adresáøe:",
	"newfolder" => "Nahrát do nového adresáøe:",
	"newfolderrecommendation" => "Doporuèení: název adresáøe by nemìl obsahovat mezery a diakritiku !",
	"allpictuploaded" => "Všechny obrázky byly nahrány na server.",
	"send" => "Odeslat",
	"and" => "a",
	"uploaderror" => "se nepodaøilo nahrát na server.",
	"nopictuploaded" => "Žádný z obrázkù se nepodaøilo na server nahrát.",
	"confirmdelete" => "Opravdu chcete odstranit tento obrázek",
	"width" => "šíøka",
	"height" => "výška",
	"aboutpic" => "Informace o obrázku",
	"size" => "velikost",
	"waitplz" => "èekejte prosím...",
	"typeofimg" => "typ",
);
 
?>