<?


$ilng = array (
	"title" => "Insert image",
	"undertitle" => "Insert image to text.",
	"imgpath" => "Image path:",
	"explore" => "Browse...",
	"alternativtext" => "Alternative text:",
	"imgtitle" => "Image title:",
	"imgsize" => "Size:",
	"imgalign" => "Align:",
	"notset" => "notset",
	"left" => "left",
	"right" => "right",
	"top" => "top",
	"bottom" => "bottom",
	"middle" => "middle",
	"absmiddle" => "abs middle",
	"absbottom" => "abs bottom",
	"baseline" => "base",
	"marginleft" => "Margin left:",
	"margintop" => "Margin top:",
	"marginbottom" => "Margin bottom:",
	"marginright" => "Margin right:",
	"border" => "Border:",
	"uploadnewimg" => "Upload new images to server",
	"insert" => "Insert",
	"cancel" => "Cancel",
	"testtext" => "Here is test text. You can change image properties and here you will see efect.",
	"explorer" => "Prohlížeè obrázkù na serveru",
	"explorerdescription" => "With this tool you can easy browse images on the server.",
	"selectdir" => "Select directory:",
	"backtoexplore" => "Back to browser",
	"uploadertoserver" => "Image uploader to server",
	"uploadertoserverdesc" => "Here you can put new images.",
	"loadingimginfo" => "Loading image info...",
	"proportions" => "proportision",
	"doaslink" => "Insert as prewiev",
	"picture" => "Image",
	"uploadtodir" => "Upload to directory:",
	"newfolder" => "Upload to a new directory:",
	"newfolderrecommendation" => "Recommendation: dont write spaces and special chars to folder name !",
	"allpictuploaded" => "All images has been uploaded to server.",
	"send" => "Send",
	"and" => "and",
	"uploaderror" => "se nepodaøilo nahrát na server.",
	"nopictuploaded" => "Error - noone image has been uploaded.",
	"confirmdelete" => "Realy yuo want to delete this image",
	"width" => "width",
	"height" => "height",
	"aboutpic" => "Image info",
	"size" => "size",
	"waitplz" => "wait please...",
	"typeofimg" => "img type",
);
 
?>